# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6.1.dev1604271126
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 750))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.deviceSettingsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceSettingsGroupBox.sizePolicy().hasHeightForWidth())
        self.deviceSettingsGroupBox.setSizePolicy(sizePolicy)
        self.deviceSettingsGroupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.deviceSettingsGroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.deviceSettingsGroupBox.setTitle("")
        self.deviceSettingsGroupBox.setObjectName("deviceSettingsGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.deviceSettingsGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.deviceIdLabel = QtWidgets.QLabel(self.deviceSettingsGroupBox)
        self.deviceIdLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deviceIdLabel.setObjectName("deviceIdLabel")
        self.gridLayout_2.addWidget(self.deviceIdLabel, 1, 1, 1, 1)
        self.deviceIdSpinBox = QtWidgets.QSpinBox(self.deviceSettingsGroupBox)
        self.deviceIdSpinBox.setMaximum(63)
        self.deviceIdSpinBox.setObjectName("deviceIdSpinBox")
        self.gridLayout_2.addWidget(self.deviceIdSpinBox, 1, 2, 1, 1)
        self.powerLabel = QtWidgets.QLabel(self.deviceSettingsGroupBox)
        self.powerLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.powerLabel.setObjectName("powerLabel")
        self.gridLayout_2.addWidget(self.powerLabel, 2, 1, 1, 1)
        self.powerSpinBox = QtWidgets.QSpinBox(self.deviceSettingsGroupBox)
        self.powerSpinBox.setMaximum(100)
        self.powerSpinBox.setSingleStep(5)
        self.powerSpinBox.setProperty("value", 60)
        self.powerSpinBox.setObjectName("powerSpinBox")
        self.gridLayout_2.addWidget(self.powerSpinBox, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.deviceSettingsGroupBox, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.normalTab = QtWidgets.QWidget()
        self.normalTab.setObjectName("normalTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.normalTab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.normalTrafficLightGroupBox = QtWidgets.QGroupBox(self.normalTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalTrafficLightGroupBox.sizePolicy().hasHeightForWidth())
        self.normalTrafficLightGroupBox.setSizePolicy(sizePolicy)
        self.normalTrafficLightGroupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.normalTrafficLightGroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.normalTrafficLightGroupBox.setTitle("")
        self.normalTrafficLightGroupBox.setObjectName("normalTrafficLightGroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.normalTrafficLightGroupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.normalRedPushButton = QtWidgets.QPushButton(self.normalTrafficLightGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.normalRedPushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.normalRedPushButton.setFont(font)
        self.normalRedPushButton.setAutoFillBackground(True)
        self.normalRedPushButton.setText("")
        self.normalRedPushButton.setFlat(True)
        self.normalRedPushButton.setObjectName("normalRedPushButton")
        self.gridLayout_6.addWidget(self.normalRedPushButton, 9, 3, 1, 1)
        self.normalYellowPushButton = QtWidgets.QPushButton(self.normalTrafficLightGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.normalYellowPushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.normalYellowPushButton.setFont(font)
        self.normalYellowPushButton.setAutoFillBackground(True)
        self.normalYellowPushButton.setText("")
        self.normalYellowPushButton.setFlat(True)
        self.normalYellowPushButton.setObjectName("normalYellowPushButton")
        self.gridLayout_6.addWidget(self.normalYellowPushButton, 10, 3, 1, 1)
        self.normalGreenLeftPushButton = QtWidgets.QPushButton(self.normalTrafficLightGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.normalGreenLeftPushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.normalGreenLeftPushButton.setFont(font)
        self.normalGreenLeftPushButton.setAutoFillBackground(True)
        self.normalGreenLeftPushButton.setFlat(True)
        self.normalGreenLeftPushButton.setObjectName("normalGreenLeftPushButton")
        self.gridLayout_6.addWidget(self.normalGreenLeftPushButton, 11, 2, 1, 1)
        self.normalGreenPushButton = QtWidgets.QPushButton(self.normalTrafficLightGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.normalGreenPushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.normalGreenPushButton.setFont(font)
        self.normalGreenPushButton.setAutoFillBackground(True)
        self.normalGreenPushButton.setFlat(True)
        self.normalGreenPushButton.setObjectName("normalGreenPushButton")
        self.gridLayout_6.addWidget(self.normalGreenPushButton, 11, 3, 1, 1)
        self.normalGreenRightPushButton = QtWidgets.QPushButton(self.normalTrafficLightGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.normalGreenRightPushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.normalGreenRightPushButton.setFont(font)
        self.normalGreenRightPushButton.setAutoFillBackground(True)
        self.normalGreenRightPushButton.setFlat(True)
        self.normalGreenRightPushButton.setObjectName("normalGreenRightPushButton")
        self.gridLayout_6.addWidget(self.normalGreenRightPushButton, 11, 4, 1, 1)
        self.verticalLayout.addWidget(self.normalTrafficLightGroupBox)
        self.tabWidget.addTab(self.normalTab, "")
        self.invertedTab = QtWidgets.QWidget()
        self.invertedTab.setObjectName("invertedTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.invertedTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.invertedTrafficLightGroupBox = QtWidgets.QGroupBox(self.invertedTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invertedTrafficLightGroupBox.sizePolicy().hasHeightForWidth())
        self.invertedTrafficLightGroupBox.setSizePolicy(sizePolicy)
        self.invertedTrafficLightGroupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.invertedTrafficLightGroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.invertedTrafficLightGroupBox.setTitle("")
        self.invertedTrafficLightGroupBox.setObjectName("invertedTrafficLightGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.invertedTrafficLightGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.invertedYellowPushButton = QtWidgets.QPushButton(self.invertedTrafficLightGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.invertedYellowPushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.invertedYellowPushButton.setFont(font)
        self.invertedYellowPushButton.setAutoFillBackground(True)
        self.invertedYellowPushButton.setText("")
        self.invertedYellowPushButton.setFlat(True)
        self.invertedYellowPushButton.setObjectName("invertedYellowPushButton")
        self.gridLayout_5.addWidget(self.invertedYellowPushButton, 10, 3, 1, 1)
        self.invertedRedPushButton = QtWidgets.QPushButton(self.invertedTrafficLightGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.invertedRedPushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.invertedRedPushButton.setFont(font)
        self.invertedRedPushButton.setAutoFillBackground(True)
        self.invertedRedPushButton.setText("")
        self.invertedRedPushButton.setFlat(True)
        self.invertedRedPushButton.setObjectName("invertedRedPushButton")
        self.gridLayout_5.addWidget(self.invertedRedPushButton, 11, 3, 1, 1)
        self.invertedGreenPushButton = QtWidgets.QPushButton(self.invertedTrafficLightGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.invertedGreenPushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.invertedGreenPushButton.setFont(font)
        self.invertedGreenPushButton.setAutoFillBackground(True)
        self.invertedGreenPushButton.setFlat(True)
        self.invertedGreenPushButton.setObjectName("invertedGreenPushButton")
        self.gridLayout_5.addWidget(self.invertedGreenPushButton, 9, 3, 1, 1)
        self.invertedGreenLeftPushButton = QtWidgets.QPushButton(self.invertedTrafficLightGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.invertedGreenLeftPushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.invertedGreenLeftPushButton.setFont(font)
        self.invertedGreenLeftPushButton.setAutoFillBackground(True)
        self.invertedGreenLeftPushButton.setFlat(True)
        self.invertedGreenLeftPushButton.setObjectName("invertedGreenLeftPushButton")
        self.gridLayout_5.addWidget(self.invertedGreenLeftPushButton, 9, 2, 1, 1)
        self.invertedGreenRightPushButton = QtWidgets.QPushButton(self.invertedTrafficLightGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.invertedGreenRightPushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.invertedGreenRightPushButton.setFont(font)
        self.invertedGreenRightPushButton.setAutoFillBackground(True)
        self.invertedGreenRightPushButton.setFlat(True)
        self.invertedGreenRightPushButton.setObjectName("invertedGreenRightPushButton")
        self.gridLayout_5.addWidget(self.invertedGreenRightPushButton, 9, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.invertedTrafficLightGroupBox)
        self.tabWidget.addTab(self.invertedTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.serialPortSettingsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialPortSettingsGroupBox.sizePolicy().hasHeightForWidth())
        self.serialPortSettingsGroupBox.setSizePolicy(sizePolicy)
        self.serialPortSettingsGroupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.serialPortSettingsGroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.serialPortSettingsGroupBox.setTitle("")
        self.serialPortSettingsGroupBox.setObjectName("serialPortSettingsGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.serialPortSettingsGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.serialPortLabel = QtWidgets.QLabel(self.serialPortSettingsGroupBox)
        self.serialPortLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.serialPortLabel.setObjectName("serialPortLabel")
        self.gridLayout_4.addWidget(self.serialPortLabel, 0, 0, 1, 1)
        self.serialPortComboBox = QtWidgets.QComboBox(self.serialPortSettingsGroupBox)
        self.serialPortComboBox.setObjectName("serialPortComboBox")
        self.gridLayout_4.addWidget(self.serialPortComboBox, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.serialPortSettingsGroupBox, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Светофор"))
        self.deviceIdLabel.setText(_translate("MainWindow", "Номер светофора:"))
        self.powerLabel.setText(_translate("MainWindow", "Мощность:"))
        self.powerSpinBox.setSuffix(_translate("MainWindow", "%"))
        self.normalGreenLeftPushButton.setText(_translate("MainWindow", "⇦"))
        self.normalGreenPushButton.setText(_translate("MainWindow", "⇧"))
        self.normalGreenRightPushButton.setText(_translate("MainWindow", "⇨"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.normalTab), _translate("MainWindow", "Нормальный"))
        self.invertedGreenPushButton.setText(_translate("MainWindow", "⇧"))
        self.invertedGreenLeftPushButton.setText(_translate("MainWindow", "⇦"))
        self.invertedGreenRightPushButton.setText(_translate("MainWindow", "⇨"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.invertedTab), _translate("MainWindow", "Перевёрнутый"))
        self.serialPortLabel.setText(_translate("MainWindow", "Последовательный порт:"))

